# fly.toml app configuration file generated for housekeeping-book on 2023-11-19T01:47:14+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "housekeeping-book"
primary_region = "nrt"
kill_signal = "SIGTERM"

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "housekeeping-book.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
