defmodule HousekeepingBook.Repo.Migrations.ChangeOnDeleteOfRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:records, "records_category_id_fkey")

    drop constraint(:records, "records_subject_id_fkey")

    alter table(:records) do
      modify :subject_id,
             references(:users,
               column: :id,
               name: "records_subject_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :nothing
             )
    end

    execute("ALTER TABLE records alter CONSTRAINT records_subject_id_fkey NOT DEFERRABLE")

    alter table(:records) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "records_category_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    execute("ALTER TABLE records alter CONSTRAINT records_category_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:records, "records_category_id_fkey")

    alter table(:records) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "records_category_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    drop constraint(:records, "records_subject_id_fkey")

    alter table(:records) do
      modify :subject_id,
             references(:users,
               column: :id,
               name: "records_subject_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end
  end
end
