defmodule HousekeepingBook.Repo.Migrations.AddUserConfirmation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :name, :text, default: "noname"
      modify :confirmed_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:users) do
      modify :confirmed_at, :utc_datetime
      modify :name, :text, default: nil
    end
  end
end
