defmodule HousekeepingBook.Repo.Migrations.TagsAndRecordsModify do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tags) do
      modify :name, :text, null: false
    end

    alter table(:records) do
      modify :amount, :bigint, default: 0
    end
  end

  def down do
    alter table(:records) do
      modify :amount, :bigint, default: nil
    end

    alter table(:tags) do
      modify :name, :text, null: true
    end
  end
end
