defmodule HousekeepingBook.Repo.Migrations.AddRecordTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:records) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :tag_ids
    # end
    # 
    create table(:record_tags, primary_key: false) do
      add :record_id,
          references(:records,
            column: :id,
            name: "record_tags_record_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "record_tags_tag_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:record_tags, "record_tags_record_id_fkey")

    drop constraint(:record_tags, "record_tags_tag_id_fkey")

    drop table(:record_tags)

    # alter table(:records) do
    # This is the `down` migration of the statement:
    #
    #     remove :tag_ids
    #
    # 
    # add :tag_ids, {:array, :bigint}
    # end
    # 
  end
end